services:
  - type: web
    name: cancer-detection-dashboard
    env: python
    plan: free
    rootDir: cancer_detection
    buildCommand: pip install -r requirements.txt && python preload_dataset.py
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0

  - type: web
    name: cifar10-native
    env: python
    plan: free
    rootDir: cifar10_cnn_classifier
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0

  - type: web
    name: cifar10-docker
    env: docker
    plan: free
    rootDir: cifar10_cnn_classifier
    dockerfilePath: Dockerfile

  - type: web
    name: vit-bhopal-chatbox
    env: static
    plan: free
    rootDir: university-rag-chatbot
    staticPublishPath: .

  - type: web
    name: car-value-predictor
    env: python
    plan: free
    rootDir: car-value-predictor
    buildCommand: pip install -r requirements.txt && python src/train.py
    startCommand: gunicorn src.server:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
