# Movies Database for Python backend

MOVIES_DATABASE = [
  {
    "id": "m1",
    "title": "Inception",
    "posterUrl": "https://image.tmdb.org/t/p/w500/9gk7adHYeZCECYV5r7t5622o0ga.jpg",
    "year": 2010,
    "genres": ["Sci-Fi", "Thriller", "Action"],
    "rating": 8.8,
    "director": "Christopher Nolan",
    "cast": ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page"],
    "duration": "2h 28m",
    "description": "A skilled thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O. to dissolve a business empire. This mind-bending heist film explores the architecture of the subconscious, layered realities, and the weight of grief and memory.",
    "keywords": ["dreams", "subconscious", "heist", "mind-bending", "architecture", "gravity", "reality", "grief"],
    "posterColor": "#1e3c72",
    "backdropGradient": "linear-gradient(135deg, #101c36 0%, #1e3c72 100%)",
    "isFeatured": True,
    "tagline": "Your mind is the scene of the crime."
  },
  {
    "id": "m2",
    "title": "Interstellar",
    "posterUrl": "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    "year": 2014,
    "genres": ["Sci-Fi", "Drama", "Adventure"],
    "rating": 8.7,
    "director": "Christopher Nolan",
    "cast": ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
    "duration": "2h 49m",
    "description": "In a near-future Earth plagued by crop blights and dust storms, a team of intrepid astronauts travels through a wormhole in search of a new home for humanity. Bridging rigorous physics concepts like relativity, time dilation, and black holes with a deeply emotional story of a father's promise to his daughter.",
    "keywords": ["space", "wormhole", "black hole", "relativity", "time dilation", "astronauts", "father-daughter", "earth collapse"],
    "posterColor": "#0b1d3a",
    "backdropGradient": "linear-gradient(135deg, #050b14 0%, #0b1d3a 100%)",
    "isFeatured": False,
    "tagline": "Mankind was born on Earth. It was never meant to die here."
  },
  {
    "id": "m3",
    "title": "The Dark Knight",
    "posterUrl": "https://image.tmdb.org/t/p/w500/qJ2tW6jUORzJy7P2mUMqv3v86sY.jpg",
    "year": 2008,
    "genres": ["Action", "Crime", "Drama"],
    "rating": 9.0,
    "director": "Christopher Nolan",
    "cast": ["Christian Bale", "Heath Ledger", "Aaron Eckhart"],
    "duration": "2h 32m",
    "description": "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice. A dark, gritty crime thriller detailing the conflict between absolute order and nihilistic chaos.",
    "keywords": ["batman", "joker", "chaos", "crime", "superhero", "vigilante", "morality", "gotham"],
    "posterColor": "#111",
    "backdropGradient": "linear-gradient(135deg, #090909 0%, #1c2331 100%)",
    "isFeatured": False,
    "tagline": "Why So Serious?"
  },
  {
    "id": "m4",
    "title": "Pulp Fiction",
    "posterUrl": "https://image.tmdb.org/t/p/w500/fIE3TL42nhDvUN2SMHABlh1695z.jpg",
    "year": 1994,
    "genres": ["Crime", "Drama"],
    "rating": 8.9,
    "director": "Quentin Tarantino",
    "cast": ["John Travolta", "Uma Thurman", "Samuel L. Jackson"],
    "duration": "2h 34m",
    "description": "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption. Famous for its highly stylized dialogue, non-linear screenplay, pop culture references, and dark humor.",
    "keywords": ["hitmen", "gangster", "nonlinear", "cult classic", "crime", "retro", "violence", "dark comedy"],
    "posterColor": "#8b0000",
    "backdropGradient": "linear-gradient(135deg, #240101 0%, #5c0606 100%)",
    "isFeatured": False,
    "tagline": "Just because you are a character doesn't mean that you have character."
  },
  {
    "id": "m5",
    "title": "The Matrix",
    "posterUrl": "https://image.tmdb.org/t/p/w500/f89U3w7n2etmqst8m4iLLy40gPv.jpg",
    "year": 1999,
    "genres": ["Sci-Fi", "Action"],
    "rating": 8.7,
    "director": "Lana Wachowski, Lilly Wachowski",
    "cast": ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"],
    "duration": "2h 16m",
    "description": "When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence. A pioneering cyberpunk film about simulated reality, AI rebellion, martial arts, and philosophical awakening.",
    "keywords": ["simulation", "cyberpunk", "hacker", "artificial intelligence", "rebellion", "dystopia", "philosophy", "bullet time"],
    "posterColor": "#003b00",
    "backdropGradient": "linear-gradient(135deg, #010f01 0%, #003b00 100%)",
    "isFeatured": False,
    "tagline": "Free your mind."
  },
  {
    "id": "m6",
    "title": "Spirited Away",
    "posterUrl": "https://image.tmdb.org/t/p/w500/393mh1e064Fiy8ynfoDeJg36t8p.jpg",
    "year": 2001,
    "genres": ["Animation", "Fantasy", "Family"],
    "rating": 8.6,
    "director": "Hayao Miyazaki",
    "cast": ["Rumi Hiiragi", "Miyu Irino", "Mari Natsuki"],
    "duration": "2h 5m",
    "description": "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts. To save her parents, she must take a job in a giant, magical bathhouse. A visually stunning, emotional fairy tale from Studio Ghibli.",
    "keywords": ["spirits", "witch", "magic", "bathhouse", "anime", "ghibli", "growing up", "fantasy"],
    "posterColor": "#224f5a",
    "backdropGradient": "linear-gradient(135deg, #0d2024 0%, #224f5a 100%)",
    "isFeatured": False,
    "tagline": "Nothing that happens is ever forgotten, even if you can't remember it."
  },
  {
    "id": "m7",
    "title": "Parasite",
    "posterUrl": "https://image.tmdb.org/t/p/w500/7IiTTjV7Ja6zkZ7XjI6vJU3kgY2.jpg",
    "year": 2019,
    "genres": ["Thriller", "Drama", "Comedy"],
    "rating": 8.5,
    "director": "Bong Joon Ho",
    "cast": ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong"],
    "duration": "2h 12m",
    "description": "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan. A brilliant dark comedy thriller that explores economic disparity, deceit, and social stratification with shocking twists.",
    "keywords": ["class divide", "wealth gap", "deception", "dark comedy", "korean", "family", "house", "secrets"],
    "posterColor": "#2d3748",
    "backdropGradient": "linear-gradient(135deg, #1a202c 0%, #3e4e68 100%)",
    "isFeatured": False,
    "tagline": "Act like you own the place."
  },
  {
    "id": "m8",
    "title": "The Shawshank Redemption",
    "posterUrl": "https://image.tmdb.org/t/p/w500/q6y0v55HG2jWb2gRCM55Z2QzRPT.jpg",
    "year": 1994,
    "genres": ["Drama"],
    "rating": 9.3,
    "director": "Frank Darabont",
    "cast": ["Tim Robbins", "Morgan Freeman", "Bob Gunton"],
    "duration": "2h 22m",
    "description": "Over the course of several years, two convicts form a friendship, seeking consolation and, eventually, redemption through basic compassion. An inspiring tale of hope, resilience, prison reform, and ultimate justice.",
    "keywords": ["prison", "hope", "friendship", "redemption", "injustice", "escape", "resilience"],
    "posterColor": "#2c3e50",
    "backdropGradient": "linear-gradient(135deg, #131c24 0%, #2c3e50 100%)",
    "isFeatured": False,
    "tagline": "Fear can hold you prisoner. Hope can set you free."
  },
  {
    "id": "m9",
    "title": "Gladiator",
    "posterUrl": "https://image.tmdb.org/t/p/w500/ty8hC42131g1w52tlyH6o2BZrVv.jpg",
    "year": 2000,
    "genres": ["Action", "Drama", "History"],
    "rating": 8.5,
    "director": "Ridley Scott",
    "cast": ["Russell Crowe", "Joaquin Phoenix", "Connie Nielsen"],
    "duration": "2h 35m",
    "description": "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery. Fighting through the brutal gladiator arenas of Rome, he captures the hearts of the populace in a epic historical drama of honor and sacrifice.",
    "keywords": ["roman empire", "vengeance", "gladiator", "arena", "general", "slavery", "honor", "epic"],
    "posterColor": "#5c3d0b",
    "backdropGradient": "linear-gradient(135deg, #1f1403 0%, #5c3d0b 100%)",
    "isFeatured": False,
    "tagline": "What we do in life echoes in eternity."
  },
  {
    "id": "m10",
    "title": "Knives Out",
    "posterUrl": "https://image.tmdb.org/t/p/w500/pThyQovXQrw2m0s56fmc9Zone1I.jpg",
    "year": 2019,
    "genres": ["Comedy", "Mystery", "Crime"],
    "rating": 7.9,
    "director": "Rian Johnson",
    "cast": ["Daniel Craig", "Chris Evans", "Ana de Armas"],
    "duration": "2h 10m",
    "description": "A detective investigates the death of a patriarch of an eccentric, combative family. A playful, modern whodunnit murder mystery full of red herrings, dry humor, clever puzzles, and social commentary on wealth and inheritance.",
    "keywords": ["detective", "murder mystery", "whodunnit", "family dispute", "inheritance", "eccentric", "humor", "puzzle"],
    "posterColor": "#4c1d95",
    "backdropGradient": "linear-gradient(135deg, #230847 0%, #4c1d95 100%)",
    "isFeatured": False,
    "tagline": "Everyone has a motive. No one has a clue."
  },
  {
    "id": "m11",
    "title": "La La Land",
    "posterUrl": "https://image.tmdb.org/t/p/w500/uDO8zWDhfNs1jNcbZ3PBF0GjJ3n.jpg",
    "year": 2016,
    "genres": ["Romance", "Musical", "Drama"],
    "rating": 8.0,
    "director": "Damien Chazelle",
    "cast": ["Ryan Gosling", "Emma Stone", "John Legend"],
    "duration": "2h 8m",
    "description": "While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future. A vibrant, colorful musical celebration of dreams, passion, heartbreak, and the compromises required to succeed in Hollywood.",
    "keywords": ["jazz", "musical", "hollywood", "dreams", "romance", "los angeles", "piano", "nostalgia"],
    "posterColor": "#be185d",
    "backdropGradient": "linear-gradient(135deg, #500724 0%, #be185d 100%)",
    "isFeatured": False,
    "tagline": "Here's to the fools who dream."
  },
  {
    "id": "m12",
    "title": "Eternal Sunshine of the Spotless Mind",
    "posterUrl": "https://image.tmdb.org/t/p/w500/5gldR6uYW4uYLDu5t52nsJNuKGm.jpg",
    "year": 2004,
    "genres": ["Romance", "Sci-Fi", "Drama"],
    "rating": 8.3,
    "director": "Michel Gondry",
    "cast": ["Jim Carrey", "Kate Winslet", "Kirsten Dunst"],
    "duration": "1h 48m",
    "description": "When their relationship turns sour, a young couple undergoes a medical procedure to have each other erased from their memories. A surreal, romantic sci-fi exploration of heartbreak, human connection, memory, and the enduring nature of love.",
    "keywords": ["memory deletion", "heartbreak", "surrealism", "romance", "indie", "relationship", "subconscious"],
    "posterColor": "#047857",
    "backdropGradient": "linear-gradient(135deg, #022c22 0%, #047857 100%)",
    "isFeatured": False,
    "tagline": "You can erase someone from your mind. Getting them out of your heart is another story."
  },
  {
    "id": "m13",
    "title": "Whiplash",
    "posterUrl": "https://image.tmdb.org/t/p/w500/oaf01Q1vi7G4nF2CviGxD44e2dO.jpg",
    "year": 2014,
    "genres": ["Drama", "Music"],
    "rating": 8.5,
    "director": "Damien Chazelle",
    "cast": ["Miles Teller", "J.K. Simmons", "Paul Reiser"],
    "duration": "1h 46m",
    "description": "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student's potential. A gripping, high-tension drama exploring obsession, teaching methods, jazz, and the sacrifices of perfection.",
    "keywords": ["drummer", "strict teacher", "jazz", "obsession", "perfection", "conservatory", "intensity", "rivalry"],
    "posterColor": "#f59e0b",
    "backdropGradient": "linear-gradient(135deg, #451a03 0%, #78350f 100%)",
    "isFeatured": True,
    "tagline": "Not quite my tempo."
  },
  {
    "id": "m14",
    "title": "Get Out",
    "posterUrl": "https://image.tmdb.org/t/p/w500/tT846Q2s2R7sveas9tC7qf84gCj.jpg",
    "year": 2017,
    "genres": ["Horror", "Mystery", "Thriller"],
    "rating": 7.8,
    "director": "Jordan Peele",
    "cast": ["Daniel Kaluuya", "Allison Williams", "Bradley Whitford"],
    "duration": "1h 44m",
    "description": "A young African-American visits his white girlfriend's parents for the weekend, where his simmering uneasiness about their reception eventually reaches a boiling point. A terrifying mystery thriller combining biting social critique, psychological horror, and mind control.",
    "keywords": ["social commentary", "racism", "mind control", "suburbia", "psychological horror", "family secrets", "escape"],
    "posterColor": "#1e1b4b",
    "backdropGradient": "linear-gradient(135deg, #0c0a0f 0%, #1e1b4b 100%)",
    "isFeatured": False,
    "tagline": "Just because you're invited, doesn't mean you're welcome."
  },
  {
    "id": "m15",
    "title": "The Grand Budapest Hotel",
    "posterUrl": "https://image.tmdb.org/t/p/w500/nX5x9Hl5y1zuiw367q5Gy7bH5Yy.jpg",
    "year": 2014,
    "genres": ["Comedy", "Drama", "Adventure"],
    "rating": 8.1,
    "director": "Wes Anderson",
    "cast": ["Ralph Fiennes", "F. Murray Abraham", "Mathieu Amalric"],
    "duration": "1h 39m",
    "description": "A writer relates his adventures at a renowned European resort hotel between the first and second World Wars with a concierge who is wrongly framed for murder. Features a highly symmetrical visual style, pastel color palettes, quirky comedy, and eccentric characters.",
    "keywords": ["wes anderson", "quirky", "symmetrical", "hotel", "heirloom", "framed for murder", "friendship", "retro"],
    "posterColor": "#db2777",
    "backdropGradient": "linear-gradient(135deg, #4d072b 0%, #db2777 100%)",
    "isFeatured": False,
    "tagline": "A perfect sanctuary for eccentric guests."
  },
  {
    "id": "m16",
    "title": "Spider-Man: Into the Spider-Verse",
    "posterUrl": "https://image.tmdb.org/t/p/w500/iiZZN63i7np468eFI684Z9n2u8v.jpg",
    "year": 2018,
    "genres": ["Animation", "Action", "Sci-Fi"],
    "rating": 8.4,
    "director": "Bob Persichetti, Peter Ramsey, Rodney Rothman",
    "cast": ["Shameik Moore", "Jake Johnson", "Hailee Steinfeld"],
    "duration": "1h 57m",
    "description": "Teen Miles Morales becomes the Spider-Man of his universe and must join with five spider-powered individuals from other dimensions to stop a threat for all realities. Celebrated for its revolutionary, comic-book-inspired animation style, diverse soundtrack, and heartfelt family message.",
    "keywords": ["multiverse", "spiderman", "animation", "superhero", "growth", "hip-hop", "alternate dimension", "family"],
    "posterColor": "#b91c1c",
    "backdropGradient": "linear-gradient(135deg, #450a0a 0%, #b91c1c 100%)",
    "isFeatured": False,
    "tagline": "Anyone can wear the mask."
  },
  {
    "id": "m17",
    "title": "Arrival",
    "posterUrl": "https://image.tmdb.org/t/p/w500/x26QjocgdCK3w24m2Ui2acrsg58.jpg",
    "year": 2016,
    "genres": ["Sci-Fi", "Drama", "Mystery"],
    "rating": 7.9,
    "director": "Denis Villeneuve",
    "cast": ["Amy Adams", "Jeremy Renner", "Forest Whitaker"],
    "duration": "1h 56m",
    "description": "A linguist is recruited by the military to assist in communicating with alien lifeforms that have arrived on Earth. As she begins to decode their non-linear language, she experiences vivid flashbacks that hold the key to the extraterrestrials' true purpose and her own future.",
    "keywords": ["aliens", "linguistics", "communication", "time travel", "first contact", "tragedy", "spacecraft"],
    "posterColor": "#1e293b",
    "backdropGradient": "linear-gradient(135deg, #0f172a 0%, #334155 100%)",
    "isFeatured": False,
    "tagline": "Why are they here?"
  },
  {
    "id": "m18",
    "title": "The Silence of the Lambs",
    "posterUrl": "https://image.tmdb.org/t/p/w500/e9ZQQwhjB62eJv9866F0cI1tS8U.jpg",
    "year": 1991,
    "genres": ["Thriller", "Crime", "Horror"],
    "rating": 8.6,
    "director": "Jonathan Demme",
    "cast": ["Jodie Foster", "Anthony Hopkins", "Lawrence A. Bonney"],
    "duration": "1h 58m",
    "description": "A young FBI cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims. An iconic psychological horror thriller detailing mind games, profiling, and institutional barriers.",
    "keywords": ["serial killer", "fbi", "cannibal", "hannibal", "mind games", "profiling", "kidnapping", "investigation"],
    "posterColor": "#4b5563",
    "backdropGradient": "linear-gradient(135deg, #111827 0%, #374151 100%)",
    "isFeatured": False,
    "tagline": "To enter the mind of a killer she must challenge the mind of a madman."
  },
  {
    "id": "m19",
    "title": "The Truman Show",
    "posterUrl": "https://image.tmdb.org/t/p/w500/vuatF4ZvG7wWzLpG4ftW53mgvLs.jpg",
    "year": 1998,
    "genres": ["Comedy", "Drama", "Sci-Fi"],
    "rating": 8.2,
    "director": "Peter Weir",
    "cast": ["Jim Carrey", "Laura Linney", "Ed Harris"],
    "duration": "1h 43m",
    "description": "An insurance salesman discovers his whole life is actually a reality television show, filmed by thousands of hidden cameras and broadcast live around the globe, with every person in his life being a paid actor. A satirical drama about surveillance, free will, and existential truth.",
    "keywords": ["reality show", "surveillance", "fake life", "escape", "existentialism", "media satire", "free will"],
    "posterColor": "#0284c7",
    "backdropGradient": "linear-gradient(135deg, #0c4a6e 0%, #0284c7 100%)",
    "isFeatured": False,
    "tagline": "On the air. Unaware."
  },
  {
    "id": "m20",
    "title": "Shutter Island",
    "posterUrl": "https://image.tmdb.org/t/p/w500/kve20wX1adzw1OI46g4slp40g63.jpg",
    "year": 2010,
    "genres": ["Mystery", "Thriller", "Drama"],
    "rating": 8.2,
    "director": "Martin Scorsese",
    "cast": ["Leonardo DiCaprio", "Mark Ruffalo", "Ben Kingsley"],
    "duration": "2h 18m",
    "description": "In 1954, a U.S. Marshal investigates the disappearance of a murderer who escaped from a hospital for the criminally insane on a remote island. As the investigation deepens, he uncovers chilling experiments and confronts his own dark past, leading to a shocking twist.",
    "keywords": ["asylum", "detective", "grief", "experiment", "hallucination", "mental illness", "island", "conspiracy"],
    "posterColor": "#334155",
    "backdropGradient": "linear-gradient(135deg, #0f172a 0%, #1e293b 100%)",
    "isFeatured": False,
    "tagline": "Someone is missing."
  },
  {
    "id": "m21",
    "title": "Superbad",
    "posterUrl": "https://image.tmdb.org/t/p/w500/ek8gozY2Yt0y8HMD3082ZlI7N8x.jpg",
    "year": 2007,
    "genres": ["Comedy"],
    "rating": 7.6,
    "director": "Greg Mottola",
    "cast": ["Jonah Hill", "Michael Cera", "Christopher Mintz-Plasse"],
    "duration": "1h 53m",
    "description": "Two co-dependent high school seniors are forced to deal with separation anxiety after their plan to stage a booze-soaked party goes awry. A hilarious, raunchy yet sweet coming-of-age comedy exploring adolescent friendship and high school graduation anxieties.",
    "keywords": ["high school", "friendship", "graduation", "party", "alcohol", "fake id", "mclovin", "coming of age"],
    "posterColor": "#ea580c",
    "backdropGradient": "linear-gradient(135deg, #431407 0%, #9a3412 100%)",
    "isFeatured": False,
    "tagline": "It is super bad. In a good way."
  },
  {
    "id": "m22",
    "title": "Dune",
    "posterUrl": "https://image.tmdb.org/t/p/w500/d5N0nFOMkw22GAsu5r56d2Cc5Yy.jpg",
    "year": 2021,
    "genres": ["Sci-Fi", "Adventure", "Drama"],
    "rating": 8.0,
    "director": "Denis Villeneuve",
    "cast": ["Timothée Chalamet", "Rebecca Ferguson", "Zendaya"],
    "duration": "2h 35m",
    "description": "A noble family becomes embroiled in a war for control of the galaxy's most valuable asset, a spice drug that extends human lifespan and enables interstellar travel, on the harsh desert planet Arrakis. An epic space opera dealing with prophecy, imperialism, ecology, and destiny.",
    "keywords": ["desert", "spice", "emperor", "prophecy", "space politics", "giant worms", "destiny", "epic"],
    "posterColor": "#78350f",
    "backdropGradient": "linear-gradient(135deg, #270e00 0%, #78350f 100%)",
    "isFeatured": False,
    "tagline": "It begins."
  },
  {
    "id": "m23",
    "title": "Everything Everywhere All at Once",
    "posterUrl": "https://image.tmdb.org/t/p/w500/w34XT1qZu4w4GvtbH6aNcnw76UP.jpg",
    "year": 2022,
    "genres": ["Sci-Fi", "Comedy", "Action", "Drama"],
    "rating": 8.7,
    "director": "Daniel Kwan, Daniel Scheinert",
    "cast": ["Michelle Yeoh", "Stephanie Hsu", "Ke Huy Quan"],
    "duration": "2h 19m",
    "description": "A middle-aged Chinese immigrant is swept up into an insane adventure in which she alone can save existence by exploring other universes and connecting with the lives she could have led. An absurd, fast-paced multiverse comedy about family, taxes, nihilism, and empathy.",
    "keywords": ["multiverse", "absurdism", "nihilism", "family", "taxes", "empathy", "taxes", "creative action"],
    "posterColor": "#4f46e5",
    "backdropGradient": "linear-gradient(135deg, #1e1b4b 0%, #312e81 100%)",
    "isFeatured": False,
    "tagline": "The universe is so much bigger than you realize."
  },
  {
    "id": "m24",
    "title": "Before Sunrise",
    "posterUrl": "https://image.tmdb.org/t/p/w500/ff195t15W3t921W5t4S5u7D2o7w.jpg",
    "year": 1995,
    "genres": ["Romance", "Drama"],
    "rating": 8.1,
    "director": "Richard Linklater",
    "cast": ["Ethan Hawke", "Julie Delpy", "Andrea Eckert"],
    "duration": "1h 41m",
    "description": "A young man and woman meet on a train in Europe, and wind up spending one evening together in Vienna, walking the streets and discussing life, love, and human connection, knowing they must separate in the morning. An intimate, talk-heavy indie romance that captures raw connection.",
    "keywords": ["vienna", "walking and talking", "intimate connection", "romance", "train meet", "time limit", "philosophy"],
    "posterColor": "#b45309",
    "backdropGradient": "linear-gradient(135deg, #451a03 0%, #92400e 100%)",
    "isFeatured": False,
    "tagline": "Can the greatest romance of your life last only one night?"
  },
  {
    "id": "m25",
    "title": "Amélie",
    "posterUrl": "https://image.tmdb.org/t/p/w500/6vX3D2o79C51n9x14798y1o0x88.jpg",
    "year": 2001,
    "genres": ["Comedy", "Romance"],
    "rating": 8.3,
    "director": "Jean-Pierre Jeunet",
    "cast": ["Audrey Tautou", "Mathieu Kassovitz", "Rufus"],
    "duration": "2h 2m",
    "description": "Amélie is an innocent and naive girl in Paris with her own sense of justice. She decides to help those around her and, along the way, discovers love. A visually whimsical, delightful French comedy filled with quirky details, warm accordion music, and magical realism.",
    "keywords": ["paris", "whimsical", "magical realism", "helping others", "quirky", "french", "love", "introvert"],
    "posterColor": "#15803d",
    "backdropGradient": "linear-gradient(135deg, #14532d 0%, #15803d 100%)",
    "isFeatured": False,
    "tagline": "She will change your life."
  },
  {
    "id": "m26",
    "title": "3 Idiots",
    "posterUrl": "https://image.tmdb.org/t/p/w500/6s1vQ5p66u3t8qZk668vD1mC5D4.jpg",
    "year": 2009,
    "genres": ["Comedy", "Drama"],
    "rating": 8.4,
    "director": "Rajkumar Hirani",
    "cast": ["Aamir Khan", "R. Madhavan", "Sharman Joshi", "Boman Irani"],
    "duration": "2h 50m",
    "description": "Two friends search for their long-lost companion. They revisit their college days and recall the memories of their friend who inspired them to think differently, even as the college administration labeled them 'idiots'. A touching comedy drama criticizing the academic system, exploring engineering student pressure, and celebrating friendship.",
    "keywords": ["college life", "friendship", "engineering", "academic pressure", "suicide prevention", "innovation", "success", "india"],
    "posterColor": "#047857",
    "backdropGradient": "linear-gradient(135deg, #064e3b 0%, #047857 100%)",
    "isFeatured": False,
    "tagline": "All is Well."
  },
  {
    "id": "m27",
    "title": "Drishyam",
    "posterUrl": "https://image.tmdb.org/t/p/w500/o71e7k8i22WvNl0Z8dJ7z77D7mE.jpg",
    "year": 2015,
    "genres": ["Thriller", "Crime", "Mystery"],
    "rating": 8.2,
    "director": "Nishikant Kamat",
    "cast": ["Ajay Devgn", "Tabu", "Shriya Saran", "Rajat Kapoor"],
    "duration": "2h 43m",
    "description": "A common cable TV operator takes desperate measures to save his family from the dark side of the law after they accidentally commit a crime. Using knowledge gathered from watching movies, he devises an airtight alibi and covers up the evidence, leading to a high-tension cat-and-mouse game with a ruthless Inspector General of Police.",
    "keywords": ["alibi", "crime cover-up", "family protection", "police investigation", "suspense", "mystery", "cat-and-mouse", "india"],
    "posterColor": "#1e293b",
    "backdropGradient": "linear-gradient(135deg, #0f172a 0%, #334155 100%)",
    "isFeatured": False,
    "tagline": "Visuals can be deceptive."
  },
  {
    "id": "m28",
    "title": "Baahubali: The Beginning",
    "posterUrl": "https://image.tmdb.org/t/p/w500/9BAjt8n8P9ZzH9VpW6bQ0O3Q88e.jpg",
    "year": 2015,
    "genres": ["Action", "Fantasy", "Drama"],
    "rating": 8.0,
    "director": "S.S. Rajamouli",
    "cast": ["Prabhas", "Rana Daggubati", "Anushka Shetty", "Tamannaah Bhatia"],
    "duration": "2h 39m",
    "description": "In ancient India, an adventurous young man named Shivudu falls in love with a warrior woman and helps her rescue her captured queen from the tyrannical ruler of the Mahishmati kingdom. Along the way, he discovers his true royal heritage and the epic story of his heroic father, Baahubali. Loaded with massive battles, mythological elements, and spectacular visual effects.",
    "keywords": ["kingdom", "royal feud", "epic battle", "mythology", "prince", "warrior", "heroism", "india"],
    "posterColor": "#b91c1c",
    "backdropGradient": "linear-gradient(135deg, #450a0a 0%, #b91c1c 100%)",
    "isFeatured": False,
    "tagline": "The story of a legend."
  },
  {
    "id": "m29",
    "title": "Gangs of Wasseypur",
    "posterUrl": "https://image.tmdb.org/t/p/w500/u91t3dZk4L2v54q4C1x6y5C8K5Z.jpg",
    "year": 2012,
    "genres": ["Crime", "Action", "Drama"],
    "rating": 8.2,
    "director": "Anurag Kashyap",
    "cast": ["Manoj Bajpayee", "Nawazuddin Siddiqui", "Richa Chadha", "Huma Qureshi"],
    "duration": "2h 40m",
    "description": "A clash between Sultan and Shahid Khan leads to the expulsion of Khan from Wasseypur, sparking a multi-generational blood feud centered around the coal mafia, power struggles, and politics. A raw, gritty, and highly stylized Indian gangland epic depicting revenge, family honor, and Dhanbad mafia wars.",
    "keywords": ["coal mafia", "family feud", "revenge", "gangster", "multi-generational", "raw action", "coal mines", "india"],
    "posterColor": "#111",
    "backdropGradient": "linear-gradient(135deg, #090909 0%, #1f1403 100%)",
    "isFeatured": False,
    "tagline": "Revenge is a dish best served cold."
  },
  {
    "id": "m30",
    "title": "RRR",
    "posterUrl": "https://image.tmdb.org/t/p/w500/w2uG79Fk620S5H752Ua4192bM9r.jpg",
    "year": 2022,
    "genres": ["Action", "Drama", "History"],
    "rating": 7.8,
    "director": "S.S. Rajamouli",
    "cast": ["N.T. Rama Rao Jr.", "Ram Charan", "Alia Bhatt", "Ajay Devgn"],
    "duration": "3h 7m",
    "description": "A fearless warrior on a secret mission and a loyal police officer serving the British Crown form an intense friendship, unaware of each other's secret identities. Set in the 1920s during the British Raj, they unite to fight against imperial tyranny in a spectacular, action-packed patriotic epic featuring wild animals, gravity-defying stunts, and the iconic Naatu Naatu dance.",
    "keywords": ["british raj", "freedom fighters", "friendship", "patriotism", "wild animals", "rebellion", "epic stunts", "india"],
    "posterColor": "#78350f",
    "backdropGradient": "linear-gradient(135deg, #270e00 0%, #78350f 100%)",
    "isFeatured": False,
    "tagline": "Rise, Roar, Revolt."
  },
  {
    "id": "m31",
    "title": "Lagaan",
    "posterUrl": "https://image.tmdb.org/t/p/w500/z6c989602C5S2l2b1q3kM7c3g21.jpg",
    "year": 2001,
    "genres": ["Drama", "History", "Sports"],
    "rating": 8.1,
    "director": "Ashutosh Gowariker",
    "cast": ["Aamir Khan", "Gracy Singh", "Rachel Shelley", "Paul Blackthorne"],
    "duration": "3h 44m",
    "description": "In Victorian India, the people of a small village stakes their future on a game of cricket against their ruthless British rulers in order to avoid paying an oppressive tax (lagaan) during a severe drought. An inspiring, Oscar-nominated drama about unity, sportsmanship, and rebellion against oppression.",
    "keywords": ["british rule", "oppressive tax", "cricket match", "drought", "unity", "sports drama", "patriotism", "india"],
    "posterColor": "#db2777",
    "backdropGradient": "linear-gradient(135deg, #4d072b 0%, #db2777 100%)",
    "isFeatured": False,
    "tagline": "Once upon a time in India."
  }
]
